# Configuração do Cloud Build para deploy automático
steps:
  # Step 1: Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 
      'gcr.io/$PROJECT_ID/sentinela:$BUILD_ID',
      '-t', 
      'gcr.io/$PROJECT_ID/sentinela:latest',
      '.'
    ]

  # Step 2: Push da imagem para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sentinela:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sentinela:latest']

  # Step 3: Deploy no Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'sentinela',
      '--image', 'gcr.io/$PROJECT_ID/sentinela:$BUILD_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '1Gi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '10',
      '--port', '8080',
      '--set-env-vars', 'ENVIRONMENT=production',
      '--timeout', '300'
    ]

# Configurações gerais
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout do build (10 minutos)
timeout: '600s'

# Substitutions para variáveis
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'sentinela'